package interfaz;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.Tablero;

public class InterfazTablero extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazTablero.class.getName());
    public ArrayList<Tablero> arrayTableros = new ArrayList<>();
    
    
    public InterfazTablero() {
        initComponents();
        //cargo tableros en un array porque es la unica manera en la que pude hacer funcionar el combobox
        for (int i = 0; i < 5; i++){
        arrayTableros.add(new Tablero());
        comboTableros.addItem("Tablero "+(i+1));
        }
         
    }
    
    public int getTablero(){
        return comboTableros.getSelectedIndex();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        comboTableros = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        lblVisitante = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        lblContVisitante = new javax.swing.JLabel();
        btnSumaVisitante = new javax.swing.JButton();
        btnRestaVisitante = new javax.swing.JButton();
        btnTerminar = new javax.swing.JButton();
        btnSumaLocal = new javax.swing.JButton();
        btnRestaLocal = new javax.swing.JButton();
        lblLocal = new javax.swing.JLabel();
        lblContLocal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tablero:");

        comboTableros.setToolTipText("");
        comboTableros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTablerosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(comboTableros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTableros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblVisitante.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblVisitante.setForeground(new java.awt.Color(0, 0, 0));
        lblVisitante.setText("Visitante");

        btnReiniciar.setBackground(new java.awt.Color(51, 51, 51));
        btnReiniciar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        lblContVisitante.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblContVisitante.setForeground(new java.awt.Color(0, 0, 0));
        lblContVisitante.setText("0");

        btnSumaVisitante.setBackground(new java.awt.Color(51, 51, 51));
        btnSumaVisitante.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSumaVisitante.setText("+");
        btnSumaVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaVisitanteActionPerformed(evt);
            }
        });

        btnRestaVisitante.setBackground(new java.awt.Color(51, 51, 51));
        btnRestaVisitante.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRestaVisitante.setText("-");
        btnRestaVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaVisitanteActionPerformed(evt);
            }
        });

        btnTerminar.setBackground(new java.awt.Color(51, 51, 51));
        btnTerminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTerminar.setText("Terminar partido");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        btnSumaLocal.setBackground(new java.awt.Color(51, 51, 51));
        btnSumaLocal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSumaLocal.setText("+");
        btnSumaLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaLocalActionPerformed(evt);
            }
        });

        btnRestaLocal.setBackground(new java.awt.Color(51, 51, 51));
        btnRestaLocal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRestaLocal.setText("-");
        btnRestaLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaLocalActionPerformed(evt);
            }
        });

        lblLocal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblLocal.setForeground(new java.awt.Color(0, 0, 0));
        lblLocal.setText("Local");

        lblContLocal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblContLocal.setForeground(new java.awt.Color(0, 0, 0));
        lblContLocal.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lblVisitante))
                    .addComponent(btnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblContLocal)
                                .addGap(85, 85, 85)
                                .addComponent(lblContVisitante)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRestaLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSumaLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSumaVisitante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRestaVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLocal)
                        .addGap(131, 131, 131)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLocal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContLocal)
                    .addComponent(lblContVisitante))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSumaLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSumaVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestaLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestaVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 311, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 16, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        int indice = getTablero();
        Tablero tablero = arrayTableros.get(indice);
        tablero.reiniciarTablero();
        lblContVisitante.setText(Integer.toString(tablero.getVisitante()));
        lblContLocal.setText(Integer.toString(tablero.getLocal()));
        
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnSumaVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaVisitanteActionPerformed
        int indice = getTablero();
        Tablero tablero = arrayTableros.get(indice);
        tablero.sumaVisita();
        lblContVisitante.setText(Integer.toString(tablero.getVisitante()));//
    }//GEN-LAST:event_btnSumaVisitanteActionPerformed

    private void btnRestaVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaVisitanteActionPerformed
        int indice = getTablero();
        Tablero tablero = arrayTableros.get(indice);
        tablero.restaVisita();
        lblContVisitante.setText(Integer.toString(tablero.getVisitante()));
    }//GEN-LAST:event_btnRestaVisitanteActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        int indice = getTablero();
        Tablero tablero = arrayTableros.get(indice);
        JOptionPane.showMessageDialog(this, tablero.quienGano());
        tablero.reiniciarTablero();
        lblContVisitante.setText(Integer.toString(tablero.getVisitante()));
        lblContLocal.setText(Integer.toString(tablero.getLocal()));
        
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void btnSumaLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaLocalActionPerformed
        int indice = getTablero();
        Tablero tablero = arrayTableros.get(indice);
        tablero.sumaLocal();
        lblContLocal.setText(Integer.toString(tablero.getLocal()));
    }//GEN-LAST:event_btnSumaLocalActionPerformed

    private void btnRestaLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaLocalActionPerformed
        int indice = getTablero();
        Tablero tablero = arrayTableros.get(indice);
        tablero.restaLocal();
        lblContLocal.setText(Integer.toString(tablero.getLocal()));
    }//GEN-LAST:event_btnRestaLocalActionPerformed

    private void comboTablerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTablerosActionPerformed
        int indice = getTablero();
        Tablero tablero = arrayTableros.get(indice);
        lblContLocal.setText(Integer.toString(tablero.getLocal()));
        lblContVisitante.setText(Integer.toString(tablero.getVisitante()));
    }//GEN-LAST:event_comboTablerosActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        Tablero tabler = new Tablero();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazTablero().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnRestaLocal;
    private javax.swing.JButton btnRestaVisitante;
    private javax.swing.JButton btnSumaLocal;
    private javax.swing.JButton btnSumaVisitante;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JComboBox<String> comboTableros;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblContLocal;
    private javax.swing.JLabel lblContVisitante;
    private javax.swing.JLabel lblLocal;
    private javax.swing.JLabel lblVisitante;
    // End of variables declaration//GEN-END:variables
}
