package interfaz;
import javax.swing.JOptionPane;
import logica.Tablero;

public class InterfazTablero extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazTablero.class.getName());

    /**
     * Creates new form intento
     */
    private Tablero tablero;
    public InterfazTablero(Tablero tablero) {
        initComponents();
        this.tablero = tablero;
        //poner nombres de los cuadros
        lblContLocal.setText(Integer.toString(tablero.getLocal())); //hacerlo texto
        //hacer el otro texto
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        lblVisitante = new javax.swing.JLabel();
        btnResultado = new javax.swing.JButton();
        lblContVisitante = new javax.swing.JLabel();
        lblNomVisitante = new javax.swing.JLabel();
        lblNomLocal = new javax.swing.JLabel();
        btnSumaVisitante = new javax.swing.JButton();
        btnRestaVisitante = new javax.swing.JButton();
        btnTerminar = new javax.swing.JButton();
        btnSumaLocal = new javax.swing.JButton();
        btnRestaLocal = new javax.swing.JButton();
        lblLocal = new javax.swing.JLabel();
        lblContLocal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tablero:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblVisitante.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblVisitante.setForeground(new java.awt.Color(0, 0, 0));
        lblVisitante.setText("Visitante");

        btnResultado.setBackground(new java.awt.Color(51, 51, 51));
        btnResultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnResultado.setText("Reiniciar");
        btnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoActionPerformed(evt);
            }
        });

        lblContVisitante.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblContVisitante.setForeground(new java.awt.Color(0, 0, 0));
        lblContVisitante.setText("0");

        lblNomVisitante.setForeground(new java.awt.Color(0, 0, 0));
        lblNomVisitante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomVisitante.setText("Nacinal");

        lblNomLocal.setForeground(new java.awt.Color(0, 0, 0));
        lblNomLocal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomLocal.setText("Peñarol");

        btnSumaVisitante.setBackground(new java.awt.Color(51, 51, 51));
        btnSumaVisitante.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSumaVisitante.setText("+");
        btnSumaVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaVisitanteActionPerformed(evt);
            }
        });

        btnRestaVisitante.setBackground(new java.awt.Color(51, 51, 51));
        btnRestaVisitante.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRestaVisitante.setText("-");
        btnRestaVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaVisitanteActionPerformed(evt);
            }
        });

        btnTerminar.setBackground(new java.awt.Color(51, 51, 51));
        btnTerminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTerminar.setText("Terminar partido");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        btnSumaLocal.setBackground(new java.awt.Color(51, 51, 51));
        btnSumaLocal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSumaLocal.setText("+");
        btnSumaLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaLocalActionPerformed(evt);
            }
        });

        btnRestaLocal.setBackground(new java.awt.Color(51, 51, 51));
        btnRestaLocal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRestaLocal.setText("-");
        btnRestaLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaLocalActionPerformed(evt);
            }
        });

        lblLocal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblLocal.setForeground(new java.awt.Color(0, 0, 0));
        lblLocal.setText("Local");

        lblContLocal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblContLocal.setForeground(new java.awt.Color(0, 0, 0));
        lblContLocal.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblLocal)
                        .addGap(32, 32, 32)
                        .addComponent(lblVisitante))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblNomLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNomVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRestaLocal, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(btnSumaLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSumaVisitante, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(btnRestaVisitante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblContLocal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblContVisitante)
                .addGap(75, 75, 75))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocal)
                    .addComponent(lblVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblContLocal))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblContVisitante)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSumaLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSumaVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestaLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestaVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 310, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoActionPerformed
        tablero.reiniciarTablero();
        lblContVisitante.setText(Integer.toString(tablero.getVisitante()));
        lblContLocal.setText(Integer.toString(tablero.getLocal()));
    }//GEN-LAST:event_btnResultadoActionPerformed

    private void btnSumaVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaVisitanteActionPerformed
        tablero.sumaVisita();
        lblContVisitante.setText(Integer.toString(tablero.getVisitante()));//
    }//GEN-LAST:event_btnSumaVisitanteActionPerformed

    private void btnRestaVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaVisitanteActionPerformed
        tablero.restaVisita();
        lblContVisitante.setText(Integer.toString(tablero.getVisitante()));
    }//GEN-LAST:event_btnRestaVisitanteActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        JOptionPane.showMessageDialog(this, tablero.quienGano());
        this.dispose();
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void btnSumaLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaLocalActionPerformed
        tablero.sumaLocal();
        lblContLocal.setText(Integer.toString(tablero.getLocal()));
    }//GEN-LAST:event_btnSumaLocalActionPerformed

    private void btnRestaLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaLocalActionPerformed
        tablero.restaLocal();
        lblContLocal.setText(Integer.toString(tablero.getLocal()));
    }//GEN-LAST:event_btnRestaLocalActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        Tablero tabler = new Tablero();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazTablero(tabler).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRestaLocal;
    private javax.swing.JButton btnRestaVisitante;
    private javax.swing.JButton btnResultado;
    private javax.swing.JButton btnSumaLocal;
    private javax.swing.JButton btnSumaVisitante;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblContLocal;
    private javax.swing.JLabel lblContVisitante;
    private javax.swing.JLabel lblLocal;
    private javax.swing.JLabel lblNomLocal;
    private javax.swing.JLabel lblNomVisitante;
    private javax.swing.JLabel lblVisitante;
    // End of variables declaration//GEN-END:variables
}
